# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nuOfuBzUKV_UDcfimQohiZDfNK2kexHZ
"""

import numpy as np
from scipy.stats import t

def evaluate_players(players, course_rates, T=0):
    """
    players: dict[str, list[float]]
        各選手のスコア
    course_rates: dict[str, list[float]]
        各選手・各ラウンドのコースレート
    T: float
        基準（0以下＝レート以上）
    """
    results = []

    for name, scores in players.items():
        scores = np.array(scores)
        rates = np.array(course_rates[name])

        if len(scores) != len(rates):
            raise ValueError(f"{name}: スコアとレートの長さが不一致")

        n = len(scores)
        if n < 2:
            raise ValueError(f"{name}: 標本サイズが小さすぎます")

        y = scores - rates   # レートとの差

        mean = y.mean()
        std = y.std(ddof=1)

        scale = std * np.sqrt(1 + 1 / n)
        df = n - 1

        prob = t.cdf((T - mean) / scale, df=df)

        results.append({
            "name": name,
            "n": n,
            "mean_diff": mean,
            "std_diff": std,
            "prob_below_rate": prob
        })

    results.sort(key=lambda x: x["prob_below_rate"], reverse=True)
    return results